# General site details
site_name: qSelf
site_url: "https://qself.gugulet.hu"
copyright: "Copyright &copy; Gugulethu Hlekwayo. All rights reserved."

# Repo info
repo_url: https://github.com/gugulet-hu/qself-process
repo_name: qself-process
edit_uri: https://github.com/gugulet-hu/qself-docs/tree/main/docs

# Theming and style details
theme:
  name: material
  language: en
  palette:
    scheme: default
    primary: custom
    accent: indigo
  font:
    text: Overpass Mono
    code: Overpass Mono
  logo: assets/qself-logo-800x800.png
  favicon: assets/qself-logo-200x200.png
  features:
    - content.code.copy
    - header.autohide
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.action.view
  icon:
    repo: fontawesome/brands/git-alt
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css: fontawesome/brands/css3
      python: fontawesome/brands/python
      logic: fontawesome/solid/robot
      database: fontawesome/solid/database
      display: fontawesome/solid/display
      analyse: fontawesome/solid/magnifying-glass-chart
      predict: fontawesome/solid/chart-mixed-up-circle-currency
      watch: fontawesome/solid/watch
      mobile: fontawesome/solid/mobile
      laptop: fontawesome/solid/laptop
extra_css:
  - stylesheets/g-theme-min.css
extra:
  generator: false
  tags:
    HTML: html
    JavaScript: js
    CSS: css
    Python: python
    Logic: logic
    Database: datatbase
    Display: display
    Analyse: analyse
    Predict: predict
    Watch: watch
    Mobile: mobile
    Laptop: laptop
  social:
    - icon: fontawesome/solid/globe
      link: https://gugulet.hu?src=qself
    - icon: fontawesome/brands/github
      link: https://github.com/gugulet-hu
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/gugulet-hu/

# Plugins
plugins:
  - search
  - tags
  - social:
      cards: true
      cards_layout_options:
        background_color: "#828089"
        font-family: Overpass Mono

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.betterem
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

## Analytics

extra_javascript:
  - path: tracking/matomo.js # For more info, see this issue: https://github.com/mkdocs/mkdocs/issues/1794
    defer: true
    async: true
