# General site details
site_name: qSelf
site_url: "https://qself.gugulet.hu"
copyright: "Copyright &copy; Gugulethu Hlekwayo. All rights reserved."

# Repo info
repo_url: https://github.com/gugulet-hu/qself-process
repo_name: qself-process
edit_uri: https://github.com/gugulet-hu/qself-docs/tree/main/docs

# Theming and style details
theme:
  name: material
  language: en
  palette:
    scheme: default
    primary: custom
    accent: indigo
  font:
    text: Overpass Mono
    code: Overpass Mono
  logo: assets/qself-logo-800x800.png
  favicon: assets/qself-logo-200x200.png
  features:
    - content.code.copy
    - header.autohide
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.action.view
  icon:
    repo: material/git
    tag:
      html: material/language-html5
      js: material/language-javascript
      css: material/language-css3
      python: material/language-python
      logic: material/robot
      database: material/database-cog
      display: material/fit-to-screen
      analyse: material/finance
      predict: material/crystal-ball
      watch: material/watch
      mobile: material/cellphone-cog
      laptop: material/laptop
extra_css:
  - stylesheets/g-theme-min.css
extra:
  generator: false
  tags:
    HTML: html
    JavaScript: js
    CSS: css
    Python: python
    Logic: logic
    Database: datatbase
    Display: display
    Analyse: analyse
    Predict: predict
    Watch: watch
    Mobile: mobile
    Laptop: laptop
  social:
    - icon: material/web
      link: https://gugulet.hu?src=qself
    - icon: material/github
      link: https://github.com/gugulet-hu
    - icon: material/linkedin
      link: https://www.linkedin.com/in/gugulet-hu/

# Plugins
plugins:
  - search
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
  - social:
      cards: true
      cards_layout_options:
        background_color: "#828089"
        font-family: Overpass Mono

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.betterem
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: false
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

## Analytics

extra_javascript:
  - path: tracking/matomo.js # For more info, see this issue: https://github.com/mkdocs/mkdocs/issues/1794
    defer: true
    async: true
